### ISSUE TITLE
Visual Studio 2015 Support

### ISSUE THREAD

**Issue by bmeverett** [Oceanware/FontSizer#1]
### Installed product versions
- Visual Studio: 2015 professional
- This extension: 1.0.6

### Description
Is there any plans to add support for VS 2015. I can work on a PR to implement this.

### Current behavior
Only available for Visual Studio 2017.

### Expected behavior
Work with other versions of Visual Studio

**Comment by kdawg1406** [comment]
@bmeverett feel free to create a new project that targets VS 2015, then use the code I've written.

I don't have VS 2015 and don't know which NuGet packages to use in this project to make it work in both.  This problem of the NuGet's between versions of VS is starting to become a pain.

Best to you,

Karl
