### ISSUE TITLE
Unneeded dependency to Visual Studio MPF 15.0

### ISSUE THREAD

**Issue by bsivanov** [Oceanware/FontSizer#2]
### Installed product versions
- Visual Studio: 2019
- This extension: 1.0.6

### Description
When trying to install the extension on Visual Studio 2019, the install requires the following dependency: **Visual Studio MPF 15.0**. According to [this blogpost](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/) of Mads Kristensen himself, and [some StackOverflow answers](https://stackoverflow.com/questions/53652152/visual-studio-2019-mpf-15-0-is-missing) this is not needed any more. 

(I can also make a pull request, but I want to confirm that this is indeed true.)

### Steps to recreate
1. Install the extension on Visual Studio 2019

### Current behavior
The installer requires **Visual Studio MPF 15.0** component to be installed.

### Expected behavior
The installer doesn't requires **Visual Studio MPF 15.0** component to be installed.

**Comment by kdawg1406** [comment]
After Resharper publishes their VS 2019 RTM release, I'll update to 2019.  

Thank you for the information.  I don't accept pull requests, just don't have the time, thank you for understanding.

**Comment by kdawg1406** [comment]
@bsivanov I spent 5 hours trying to upgrade this extension.  I've given up.  If you want to continue to use this, please make any changes you need to be successful.
